<?php /* Smarty version Smarty-3.1.14, created on 2022-04-01 10:14:47
         compiled from "/home/miricouz/xx.uz/wa-apps/shop/templates/actions/frontend/order/form/region.html" */ ?>
<?php /*%%SmartyHeaderCode:10370373462468a4782bf53-56026496%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'b03eddf0b1aa632020700b653e199e5dd8e18dae' => 
    array (
      0 => '/home/miricouz/xx.uz/wa-apps/shop/templates/actions/frontend/order/form/region.html',
      1 => 1626346255,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '10370373462468a4782bf53-56026496',
  'function' => 
  array (
    '_echo_size_class' => 
    array (
      'parameter' => 
      array (
        '_size' => '',
      ),
      'compiled' => '',
    ),
    '_render_label' => 
    array (
      'parameter' => 
      array (
        '_label' => '',
        '_required' => false,
      ),
      'compiled' => '',
    ),
  ),
  'variables' => 
  array (
    'config' => 0,
    'error_step_id' => 0,
    'errors' => 0,
    'region' => 0,
    '_location' => 0,
    '_active_location' => 0,
    '_size' => 0,
    '_size_class' => 0,
    '_required' => 0,
    '_label' => 0,
    '_system_address_field_names' => 0,
    '_is_zip_required' => 0,
    '_hide_region' => 0,
    '_config' => 0,
    '_is_minimal_mode' => 0,
    '_is_default_mode' => 0,
    '_is_country_required' => 0,
    '_countries' => 0,
    '_is_active_set' => 0,
    '_country' => 0,
    '_is_active' => 0,
    '_active_county' => 0,
    '_active_country_id' => 0,
    '_is_region_required' => 0,
    '_active_region_id' => 0,
    '_region' => 0,
    '_region_value' => 0,
    '_active_region' => 0,
    '_is_city_required' => 0,
    '_active_city_id' => 0,
    '_city' => 0,
    '_city_value' => 0,
    '_active_city' => 0,
    '_zip_field' => 0,
    '_nothing_to_change' => 0,
    '_active_region_value' => 0,
    '_active_city_value' => 0,
    'event_hook' => 0,
    '_' => 0,
    '_errors' => 0,
  ),
  'has_nocache_code' => 0,
  'version' => 'Smarty-3.1.14',
  'unifunc' => 'content_62468a47a3f124_34562173',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_62468a47a3f124_34562173')) {function content_62468a47a3f124_34562173($_smarty_tpl) {?><?php $_smarty_tpl->tpl_vars['_config'] = new Smarty_variable($_smarty_tpl->tpl_vars['config']->value['shipping'], null, 0);?><?php $_smarty_tpl->tpl_vars['_system_address_field_names'] = new Smarty_variable($_smarty_tpl->tpl_vars['config']->value->getSystemAddressFieldNames(), null, 0);?><?php $_smarty_tpl->tpl_vars['_errors'] = new Smarty_variable(array(), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['error_step_id']->value)&&$_smarty_tpl->tpl_vars['error_step_id']->value==="region"){?><?php $_smarty_tpl->tpl_vars['_errors'] = new Smarty_variable($_smarty_tpl->tpl_vars['errors']->value, null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['_countries'] = new Smarty_variable(array(), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['countries'])){?><?php $_smarty_tpl->tpl_vars['_countries'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['countries'], null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['_active_location'] = new Smarty_variable(null, null, 0);?><?php $_smarty_tpl->tpl_vars['_active_county'] = new Smarty_variable(null, null, 0);?><?php $_smarty_tpl->tpl_vars['_active_region'] = new Smarty_variable(null, null, 0);?><?php if (isset($_smarty_tpl->tpl_vars['region']->value['selected_values']['location_id'])){?><?php  $_smarty_tpl->tpl_vars['_location'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_location']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['region']->value['locations']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_location']->key => $_smarty_tpl->tpl_vars['_location']->value){
$_smarty_tpl->tpl_vars['_location']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_location']->value['id']==$_smarty_tpl->tpl_vars['region']->value['selected_values']['location_id']){?><?php $_smarty_tpl->tpl_vars['_active_location'] = new Smarty_variable($_smarty_tpl->tpl_vars['_location']->value, null, 0);?><?php }?><?php } ?><?php if (empty($_smarty_tpl->tpl_vars['_active_location']->value)){?><?php $_smarty_tpl->tpl_vars['_active_location'] = new Smarty_variable(reset($_smarty_tpl->tpl_vars['region']->value['locations']), null, 0);?><?php }?><?php }?><?php $_smarty_tpl->tpl_vars['_is_default_mode'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_minimal_mode'] = new Smarty_variable(false, null, 0);?><?php if ($_smarty_tpl->tpl_vars['config']->value['shipping']['mode']==shopCheckoutConfig::SHIPPING_MODE_TYPE_MINIMUM){?><?php $_smarty_tpl->tpl_vars['_is_default_mode'] = new Smarty_variable(false, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_minimal_mode'] = new Smarty_variable(true, null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['_is_country_required'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_region_required'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_city_required'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_zip_required'] = new Smarty_variable(true, null, 0);?><?php if (!function_exists('smarty_template_function__echo_size_class')) {
    function smarty_template_function__echo_size_class($_smarty_tpl,$params) {
    $saved_tpl_vars = $_smarty_tpl->tpl_vars;
    foreach ($_smarty_tpl->smarty->template_functions['_echo_size_class']['parameter'] as $key => $value) {$_smarty_tpl->tpl_vars[$key] = new Smarty_variable($value);};
    foreach ($params as $key => $value) {$_smarty_tpl->tpl_vars[$key] = new Smarty_variable($value);}?><?php $_smarty_tpl->tpl_vars['_size_class'] = new Smarty_variable("size-medium", null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_size']->value)){?><?php if ($_smarty_tpl->tpl_vars['_size']->value==shopCheckoutConfig::FIELD_WIDTH_MINI){?><?php $_smarty_tpl->tpl_vars['_size_class'] = new Smarty_variable("size-mini", null, 0);?><?php }elseif($_smarty_tpl->tpl_vars['_size']->value==shopCheckoutConfig::FIELD_WIDTH_SMALL){?><?php $_smarty_tpl->tpl_vars['_size_class'] = new Smarty_variable("size-small", null, 0);?><?php }elseif($_smarty_tpl->tpl_vars['_size']->value==shopCheckoutConfig::FIELD_WIDTH_MEDIUM){?><?php $_smarty_tpl->tpl_vars['_size_class'] = new Smarty_variable("size-medium", null, 0);?><?php }elseif($_smarty_tpl->tpl_vars['_size']->value==shopCheckoutConfig::FIELD_WIDTH_LARGE){?><?php $_smarty_tpl->tpl_vars['_size_class'] = new Smarty_variable("size-large", null, 0);?><?php }?><?php }?><?php echo $_smarty_tpl->tpl_vars['_size_class']->value;?>
<?php $_smarty_tpl->tpl_vars = $saved_tpl_vars;
foreach (Smarty::$global_tpl_vars as $key => $value) if(!isset($_smarty_tpl->tpl_vars[$key])) $_smarty_tpl->tpl_vars[$key] = $value;}}?>
<?php if (!function_exists('smarty_template_function__render_label')) {
    function smarty_template_function__render_label($_smarty_tpl,$params) {
    $saved_tpl_vars = $_smarty_tpl->tpl_vars;
    foreach ($_smarty_tpl->smarty->template_functions['_render_label']['parameter'] as $key => $value) {$_smarty_tpl->tpl_vars[$key] = new Smarty_variable($value);};
    foreach ($params as $key => $value) {$_smarty_tpl->tpl_vars[$key] = new Smarty_variable($value);}?><?php if (!empty($_smarty_tpl->tpl_vars['_required']->value)){?><span class="wa-tooltip is-inline top" data-title="Required field"><?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_label']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
<span class="wa-required"></span></span><?php }else{ ?><?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_label']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
<?php }?><?php $_smarty_tpl->tpl_vars = $saved_tpl_vars;
foreach (Smarty::$global_tpl_vars as $key => $value) if(!isset($_smarty_tpl->tpl_vars[$key])) $_smarty_tpl->tpl_vars[$key] = $value;}}?>
<?php $_smarty_tpl->_capture_stack[0][] = array('default', "_zip_field", null); ob_start(); ?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['ask_zip'])){?><div class="wa-field-wrapper wa-zip-wrapper <?php smarty_template_function__echo_size_class($_smarty_tpl,array('_size'=>shopCheckoutConfig::FIELD_WIDTH_MINI));?>
"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>$_smarty_tpl->tpl_vars['_system_address_field_names']->value['zip'],'_required'=>!empty($_smarty_tpl->tpl_vars['_is_zip_required']->value)));?>
</label><input class="wa-input js-zip-field" autocomplete="false" name="region[zip]" type="text" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['region']->value['selected_values']['zip'])===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_zip_required']->value)){?>required<?php }?>></div><?php }?><?php list($_capture_buffer, $_capture_assign, $_capture_append) = array_pop($_smarty_tpl->_capture_stack[0]);
if (!empty($_capture_buffer)) {
 if (isset($_capture_assign)) $_smarty_tpl->assign($_capture_assign, ob_get_contents());
 if (isset( $_capture_append)) $_smarty_tpl->append( $_capture_append, ob_get_contents());
 Smarty::$_smarty_vars['capture'][$_capture_buffer]=ob_get_clean();
} else $_smarty_tpl->capture_error();?><?php $_smarty_tpl->tpl_vars['_hide_region'] = new Smarty_variable(!empty($_smarty_tpl->tpl_vars['_hide_region']->value)||!empty($_smarty_tpl->tpl_vars['region']->value['disabled']), null, 0);?><section class="wa-step-section wa-step-region-section" id="wa-step-region-section" style="<?php if (!empty($_smarty_tpl->tpl_vars['_hide_region']->value)){?>display: none;<?php }?>"><header class="wa-section-header"><h3 class="wa-header"><?php echo $_smarty_tpl->tpl_vars['_config']->value['block_name'];?>
</h3></header><?php $_smarty_tpl->tpl_vars['_nothing_to_change'] = new Smarty_variable(false, null, 0);?><?php if ($_smarty_tpl->tpl_vars['_is_minimal_mode']->value&&isset($_smarty_tpl->tpl_vars['region']->value['locations'])&&count($_smarty_tpl->tpl_vars['region']->value['locations'])===1){?><?php if (!empty($_smarty_tpl->tpl_vars['_active_location']->value['country_id'])&&!(empty($_smarty_tpl->tpl_vars['_active_location']->value['region_id'])&&empty($_smarty_tpl->tpl_vars['_active_location']->value['region']))&&!(empty($_smarty_tpl->tpl_vars['_active_location']->value['city_id'])&&empty($_smarty_tpl->tpl_vars['_active_location']->value['city']))&&empty($_smarty_tpl->tpl_vars['region']->value['ask_zip'])){?><?php $_smarty_tpl->tpl_vars['_nothing_to_change'] = new Smarty_variable(true, null, 0);?><?php }?><?php }?><div class="wa-section-body"><form autocomplete="off"><?php if (empty($_smarty_tpl->tpl_vars['region']->value['disabled'])){?><div class="wa-line wa-required-text"><span class="wa-required"></span>To view shipping cost and estimated shipping time, please complete fields with an asterisk</div><?php if ($_smarty_tpl->tpl_vars['_is_default_mode']->value){?><div class="wa-line wa-fields-group line"><input name="region[location_id]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_location']->value['id'])===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><div class="wa-field-wrapper wa-country-wrapper <?php smarty_template_function__echo_size_class($_smarty_tpl,array('_size'=>shopCheckoutConfig::FIELD_WIDTH_MEDIUM));?>
"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>$_smarty_tpl->tpl_vars['_system_address_field_names']->value['country'],'_required'=>!empty($_smarty_tpl->tpl_vars['_is_country_required']->value)));?>
</label><?php if (empty($_smarty_tpl->tpl_vars['_active_location']->value['country_locked'])){?><select class="wa-select js-country-field" name="region[country]" <?php if (!empty($_smarty_tpl->tpl_vars['_is_country_required']->value)){?>required<?php }?>><option value="" disabled <?php if (empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id'])){?>selected<?php }?>>Select a country</option><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(false, null, 0);?><?php  $_smarty_tpl->tpl_vars['_country'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_country']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_countries']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_country']->key => $_smarty_tpl->tpl_vars['_country']->value){
$_smarty_tpl->tpl_vars['_country']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(false, null, 0);?><?php if (empty($_smarty_tpl->tpl_vars['_is_active_set']->value)&&$_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id']==$_smarty_tpl->tpl_vars['_country']->value['id']){?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_active_county'] = new Smarty_variable($_smarty_tpl->tpl_vars['_country']->value, null, 0);?><?php }?><?php if (empty($_smarty_tpl->tpl_vars['_country']->value['id'])){?><option value="" disabled></option><?php }else{ ?><option value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_country']->value['id'], ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_active']->value)){?>selected<?php }?>><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_country']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
</option><?php }?><?php } ?></select><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_active_country_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['country_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id'])){?><?php $_smarty_tpl->tpl_vars['_active_country_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id'], null, 0);?><?php  $_smarty_tpl->tpl_vars['_country'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_country']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_countries']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_country']->key => $_smarty_tpl->tpl_vars['_country']->value){
$_smarty_tpl->tpl_vars['_country']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id']==$_smarty_tpl->tpl_vars['_country']->value['id']){?><?php $_smarty_tpl->tpl_vars['_active_county'] = new Smarty_variable($_smarty_tpl->tpl_vars['_country']->value, null, 0);?><?php break 1?><?php }?><?php } ?><?php }?><input class="wa-input" type="text" value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_active_county']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
" disabled><input name="region[country]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_country_id']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }?></div><div class="wa-field-wrapper wa-region-wrapper <?php smarty_template_function__echo_size_class($_smarty_tpl,array('_size'=>shopCheckoutConfig::FIELD_WIDTH_MEDIUM));?>
"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>$_smarty_tpl->tpl_vars['_system_address_field_names']->value['region'],'_required'=>!empty($_smarty_tpl->tpl_vars['_is_region_required']->value)));?>
</label><?php if (empty($_smarty_tpl->tpl_vars['_active_location']->value['region_locked'])){?><?php if (!empty($_smarty_tpl->tpl_vars['_active_county']->value['has_regions'])){?><?php $_smarty_tpl->tpl_vars['_active_region_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['region_id'])){?><?php $_smarty_tpl->tpl_vars['_active_region_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['region_id'], null, 0);?><?php }?><select class="wa-select js-region-field js-region-field-id" name="region[region]" <?php if (!empty($_smarty_tpl->tpl_vars['_is_region_required']->value)){?>required<?php }?>><option value="" disabled <?php if (empty($_smarty_tpl->tpl_vars['_active_region_id']->value)){?>selected<?php }?>>Select a region</option><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(false, null, 0);?><?php  $_smarty_tpl->tpl_vars['_region'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_region']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_active_county']->value['regions']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_region']->key => $_smarty_tpl->tpl_vars['_region']->value){
$_smarty_tpl->tpl_vars['_region']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(false, null, 0);?><?php if (empty($_smarty_tpl->tpl_vars['_is_active_set']->value)&&$_smarty_tpl->tpl_vars['_active_region_id']->value==$_smarty_tpl->tpl_vars['_region']->value['id']){?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_active_region'] = new Smarty_variable($_smarty_tpl->tpl_vars['_region']->value, null, 0);?><?php }?><?php if (empty($_smarty_tpl->tpl_vars['_region']->value['id'])){?><option value="" disabled></option><?php }else{ ?><option value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_region']->value['id'], ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_active']->value)){?>selected<?php }?>><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_region']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
</option><?php }?><?php } ?></select><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['region'])){?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['region'], null, 0);?><?php }?><input class="wa-input js-region-field js-region-field-value" autocomplete="false" name="region[region]" type="text" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_region_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_region_required']->value)){?>required<?php }?>><?php }?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_active_region_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['region_id'])){?><?php $_smarty_tpl->tpl_vars['_active_region_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['region_id'], null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['region'])){?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['region'], null, 0);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['_active_region_id']->value)){?><?php  $_smarty_tpl->tpl_vars['_region'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_region']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_active_county']->value['regions']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_region']->key => $_smarty_tpl->tpl_vars['_region']->value){
$_smarty_tpl->tpl_vars['_region']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_active_region_id']->value==$_smarty_tpl->tpl_vars['_region']->value['id']){?><?php $_smarty_tpl->tpl_vars['_active_region'] = new Smarty_variable($_smarty_tpl->tpl_vars['_region']->value, null, 0);?><?php }?><?php } ?><input class="wa-input" type="text" value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_active_region']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
" disabled><input class="js-region-field-id" name="region[region]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_region_id']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }else{ ?><input class="wa-input" type="text" value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_region_value']->value, ENT_QUOTES, 'UTF-8', true);?>
" disabled><input class="js-region-field-value" name="region[region]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_region_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }?><?php }?></div><div class="wa-field-wrapper wa-city-wrapper <?php smarty_template_function__echo_size_class($_smarty_tpl,array('_size'=>shopCheckoutConfig::FIELD_WIDTH_MEDIUM));?>
"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>$_smarty_tpl->tpl_vars['_system_address_field_names']->value['city'],'_required'=>!empty($_smarty_tpl->tpl_vars['_is_city_required']->value)));?>
</label><?php if (empty($_smarty_tpl->tpl_vars['_active_location']->value['city_locked'])){?><?php if (!empty($_smarty_tpl->tpl_vars['_active_region']->value['has_cities'])){?><?php $_smarty_tpl->tpl_vars['_active_city_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['city_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['city_id'])){?><?php $_smarty_tpl->tpl_vars['_active_city_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['city_id'], null, 0);?><?php }?><select class="wa-select js-city-field" name="region[city_id]" <?php if (!empty($_smarty_tpl->tpl_vars['_is_city_required']->value)){?>required<?php }?>><option value="" disabled <?php if (empty($_smarty_tpl->tpl_vars['_active_city_id']->value)){?>selected<?php }?>>Select a locality</option><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(false, null, 0);?><?php  $_smarty_tpl->tpl_vars['_city'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_city']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_active_region']->value['cities']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_city']->key => $_smarty_tpl->tpl_vars['_city']->value){
$_smarty_tpl->tpl_vars['_city']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(false, null, 0);?><?php if (empty($_smarty_tpl->tpl_vars['_is_active_set']->value)&&$_smarty_tpl->tpl_vars['_active_city_id']->value==$_smarty_tpl->tpl_vars['_city']->value['id']){?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(true, null, 0);?><?php }?><?php if (empty($_smarty_tpl->tpl_vars['_city']->value['id'])){?><option value="" disabled></option><?php }else{ ?><option value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_city']->value['id'], ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_active']->value)){?>selected<?php }?>><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_city']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
</option><?php }?><?php } ?></select><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable(ifset($_smarty_tpl->tpl_vars['_active_location']->value,'city',null), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['city'])){?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['city'], null, 0);?><?php }?><input class="wa-input js-city-field js-city-autocomplete" autocomplete="false" name="region[city]" type="text" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_city_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_city_required']->value)){?>required<?php }?>><?php }?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_active_city_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['city_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['city_id'])){?><?php $_smarty_tpl->tpl_vars['_active_city_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['city_id'], null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['city'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['city'])){?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['city'], null, 0);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['_active_city_id']->value)){?><?php $_smarty_tpl->tpl_vars['_active_city'] = new Smarty_variable(null, null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_active_region']->value)){?><?php  $_smarty_tpl->tpl_vars['_city'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_city']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_active_region']->value['cities']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_city']->key => $_smarty_tpl->tpl_vars['_city']->value){
$_smarty_tpl->tpl_vars['_city']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_active_city_id']->value==$_smarty_tpl->tpl_vars['_city']->value['id']){?><?php $_smarty_tpl->tpl_vars['_active_city'] = new Smarty_variable($_smarty_tpl->tpl_vars['_city']->value, null, 0);?><?php break 1?><?php }?><?php } ?><?php }?><input class="wa-input" type="text" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_city']->value['name'])===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
" disabled><input name="region[city_id]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_city_id']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }else{ ?><input class="wa-input" type="text" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_city_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
" disabled><input name="region[city]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_city_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }?><?php }?></div><?php echo $_smarty_tpl->tpl_vars['_zip_field']->value;?>
</div><?php }elseif($_smarty_tpl->tpl_vars['_is_minimal_mode']->value){?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_active_location']->value['region'])){?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region'], null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['city_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_active_location']->value['city'])){?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['city'], null, 0);?><?php }?><div class="wa-line wa-fields-group line" <?php if (!empty($_smarty_tpl->tpl_vars['_nothing_to_change']->value)){?>style="display: none;"<?php }?>><?php if (count($_smarty_tpl->tpl_vars['region']->value['locations'])>1){?><div class="wa-field-wrapper wa-location-wrapper size-medium"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>"Shipping area",'_required'=>true));?>
</label><select class="wa-select js-location-field" name="region[location_id]" required><?php  $_smarty_tpl->tpl_vars['_location'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_location']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['region']->value['locations']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_location']->key => $_smarty_tpl->tpl_vars['_location']->value){
$_smarty_tpl->tpl_vars['_location']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(false, null, 0);?><?php if ($_smarty_tpl->tpl_vars['_active_location']->value['id']==$_smarty_tpl->tpl_vars['_location']->value['id']){?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(true, null, 0);?><?php }?><option value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_location']->value['id'], ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_active']->value)){?>selected<?php }?>><?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_location']->value['name'])===null||$tmp==='' ? "No name" : $tmp), ENT_QUOTES, 'UTF-8', true);?>
</option><?php } ?></select></div><?php }else{ ?><input name="region[location_id]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_location']->value['id'])===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }?><?php $_smarty_tpl->tpl_vars['_active_country_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['country_id'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_active_country_id']->value)){?><input class="js-country-field" name="region[country]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_country_id']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php  $_smarty_tpl->tpl_vars['_country'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_country']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_countries']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_country']->key => $_smarty_tpl->tpl_vars['_country']->value){
$_smarty_tpl->tpl_vars['_country']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id']==$_smarty_tpl->tpl_vars['_country']->value['id']){?><?php $_smarty_tpl->tpl_vars['_active_county'] = new Smarty_variable($_smarty_tpl->tpl_vars['_country']->value, null, 0);?><?php break 1?><?php }?><?php } ?><?php }else{ ?><div class="wa-field-wrapper wa-country-wrapper <?php smarty_template_function__echo_size_class($_smarty_tpl,array('_size'=>shopCheckoutConfig::FIELD_WIDTH_MEDIUM));?>
"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>$_smarty_tpl->tpl_vars['_system_address_field_names']->value['country'],'_required'=>!empty($_smarty_tpl->tpl_vars['_is_country_required']->value)));?>
</label><select class="wa-select js-country-field" name="region[country]" <?php if (!empty($_smarty_tpl->tpl_vars['_is_country_required']->value)){?>required<?php }?>><option value="" disabled <?php if (empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id'])){?>selected<?php }?>>Select a country</option><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(false, null, 0);?><?php  $_smarty_tpl->tpl_vars['_country'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_country']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_countries']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_country']->key => $_smarty_tpl->tpl_vars['_country']->value){
$_smarty_tpl->tpl_vars['_country']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(false, null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_is_active_set']->value)&&$_smarty_tpl->tpl_vars['region']->value['selected_values']['country_id']==$_smarty_tpl->tpl_vars['_country']->value['id']){?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_active_county'] = new Smarty_variable($_smarty_tpl->tpl_vars['_country']->value, null, 0);?><?php }?><?php if (empty($_smarty_tpl->tpl_vars['_country']->value['id'])){?><option value="" disabled></option><?php }else{ ?><option value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_country']->value['id'], ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_active']->value)){?>selected<?php }?>><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_country']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
</option><?php }?><?php } ?></select></div><?php }?><?php $_smarty_tpl->tpl_vars['_active_region_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region_id'], null, 0);?><?php $_smarty_tpl->tpl_vars['_active_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['region'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_active_region_id']->value)){?><input class="js-region-field js-region-field-id" name="region[region]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_region_id']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }elseif(!empty($_smarty_tpl->tpl_vars['_active_region_value']->value)){?><input class="js-region-field js-region-field-value" name="region[region]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_region_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }else{ ?><div class="wa-field-wrapper wa-region-wrapper <?php smarty_template_function__echo_size_class($_smarty_tpl,array('_size'=>shopCheckoutConfig::FIELD_WIDTH_MEDIUM));?>
"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>$_smarty_tpl->tpl_vars['_system_address_field_names']->value['region'],'_required'=>!empty($_smarty_tpl->tpl_vars['_is_region_required']->value)));?>
</label><?php if (!empty($_smarty_tpl->tpl_vars['_active_county']->value['has_regions'])){?><?php $_smarty_tpl->tpl_vars['_active_region_id'] = new Smarty_variable(null, null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['region_id'])){?><?php $_smarty_tpl->tpl_vars['_active_region_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['region_id'], null, 0);?><?php }?><select class="wa-select js-region-field js-region-field-id" name="region[region]" <?php if (!empty($_smarty_tpl->tpl_vars['_is_region_required']->value)){?>required<?php }?>><option value="" disabled <?php if (empty($_smarty_tpl->tpl_vars['_active_region_id']->value)){?>selected<?php }?>>Select a region</option><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(false, null, 0);?><?php  $_smarty_tpl->tpl_vars['_region'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_region']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_active_county']->value['regions']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_region']->key => $_smarty_tpl->tpl_vars['_region']->value){
$_smarty_tpl->tpl_vars['_region']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(false, null, 0);?><?php if (empty($_smarty_tpl->tpl_vars['_is_active_set']->value)&&$_smarty_tpl->tpl_vars['_active_region_id']->value==$_smarty_tpl->tpl_vars['_region']->value['id']){?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_active_region'] = new Smarty_variable($_smarty_tpl->tpl_vars['_region']->value, null, 0);?><?php }?><?php if (empty($_smarty_tpl->tpl_vars['_region']->value['id'])){?><option value="" disabled></option><?php }else{ ?><option value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_region']->value['id'], ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_active']->value)){?>selected<?php }?>><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_region']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
</option><?php }?><?php } ?></select><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable(null, null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['region']->value['selected_values']['region'])){?><?php $_smarty_tpl->tpl_vars['_region_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['region'], null, 0);?><?php }?><input class="wa-input js-region-field js-region-field-value" autocomplete="false" name="region[region]" type="text" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_region_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_region_required']->value)){?>required<?php }?>><?php }?></div><?php }?><?php $_smarty_tpl->tpl_vars['_active_city_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['city_id'], null, 0);?><?php $_smarty_tpl->tpl_vars['_active_city_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['_active_location']->value['city'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_active_city_id']->value)){?><input class="js-city-field" name="region[city_id]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_city_id']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }elseif(!empty($_smarty_tpl->tpl_vars['_active_city_value']->value)){?><input class="js-city-field" name="region[city]" type="hidden" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_active_city_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
"><?php }else{ ?><div class="wa-field-wrapper wa-city-wrapper <?php smarty_template_function__echo_size_class($_smarty_tpl,array('_size'=>shopCheckoutConfig::FIELD_WIDTH_MEDIUM));?>
"><label class="wa-label"><?php smarty_template_function__render_label($_smarty_tpl,array('_label'=>$_smarty_tpl->tpl_vars['_system_address_field_names']->value['city'],'_required'=>!empty($_smarty_tpl->tpl_vars['_is_city_required']->value)));?>
</label><?php if (!empty($_smarty_tpl->tpl_vars['_active_region']->value['has_cities'])){?><?php $_smarty_tpl->tpl_vars['_active_city_id'] = new Smarty_variable(null, null, 0);?><?php if (isset($_smarty_tpl->tpl_vars['region']->value['selected_values']['city_id'])){?><?php $_smarty_tpl->tpl_vars['_active_city_id'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['city_id'], null, 0);?><?php }?><select class="wa-select js-city-field" name="region[city_id]" <?php if (!empty($_smarty_tpl->tpl_vars['_is_city_required']->value)){?>required<?php }?>><option value="" disabled <?php if (empty($_smarty_tpl->tpl_vars['_active_city_id']->value)){?>selected<?php }?>>Select a locality</option><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(false, null, 0);?><?php  $_smarty_tpl->tpl_vars['_city'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_city']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_active_region']->value['cities']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_city']->key => $_smarty_tpl->tpl_vars['_city']->value){
$_smarty_tpl->tpl_vars['_city']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(false, null, 0);?><?php if (empty($_smarty_tpl->tpl_vars['_is_active_set']->value)&&$_smarty_tpl->tpl_vars['_active_city_id']->value==$_smarty_tpl->tpl_vars['_city']->value['id']){?><?php $_smarty_tpl->tpl_vars['_is_active'] = new Smarty_variable(true, null, 0);?><?php $_smarty_tpl->tpl_vars['_is_active_set'] = new Smarty_variable(false, null, 0);?><?php }?><?php if (empty($_smarty_tpl->tpl_vars['_city']->value['id'])){?><option value="" disabled></option><?php }else{ ?><option value="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_city']->value['id'], ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_active']->value)){?>selected<?php }?>><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['_city']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
</option><?php }?><?php } ?></select><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable(null, null, 0);?><?php if (isset($_smarty_tpl->tpl_vars['region']->value['selected_values']['city'])){?><?php $_smarty_tpl->tpl_vars['_city_value'] = new Smarty_variable($_smarty_tpl->tpl_vars['region']->value['selected_values']['city'], null, 0);?><?php }?><input class="wa-input js-city-field js-city-autocomplete" autocomplete="false" name="region[city]" type="text" value="<?php echo htmlspecialchars((($tmp = @$_smarty_tpl->tpl_vars['_city_value']->value)===null||$tmp==='' ? '' : $tmp), ENT_QUOTES, 'UTF-8', true);?>
" <?php if (!empty($_smarty_tpl->tpl_vars['_is_city_required']->value)){?>required<?php }?>><?php }?></div><?php }?><?php echo $_smarty_tpl->tpl_vars['_zip_field']->value;?>
</div><?php }?><?php  $_smarty_tpl->tpl_vars['_'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['event_hook']->value['region']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_']->key => $_smarty_tpl->tpl_vars['_']->value){
$_smarty_tpl->tpl_vars['_']->_loop = true;
?><div class="wa-plugin-hook"><?php echo $_smarty_tpl->tpl_vars['_']->value;?>
</div><?php } ?><?php }?></form></div><script>( function($) {var $section = $("#wa-step-region-section"),$wrapper = $("#wa-order-form-wrapper");var ready_promise = $wrapper.data("ready").promise();ready_promise.then( function(controller) {controller.initRegion({$wrapper: $section,disabled: <?php if (!empty($_smarty_tpl->tpl_vars['region']->value['disabled'])){?>true<?php }else{ ?>false<?php }?>,auto_use_timeout: <?php if (!empty($_smarty_tpl->tpl_vars['_config']->value['auto_use_timeout'])&&($_smarty_tpl->tpl_vars['_config']->value['auto_use_timeout']>0)){?><?php echo $_smarty_tpl->tpl_vars['_config']->value['auto_use_timeout']*1000;?>
<?php }else{ ?>0<?php }?>,errors: <?php echo json_encode($_smarty_tpl->tpl_vars['_errors']->value);?>
});});})(jQuery);</script></section><?php }} ?>